{"errorMessage": "An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.", "errorType": "NoSuchKey", "requestId": "9f10ff0c-db3c-4f8c-a80a-60beb51e81a2", "stackTrace": ["  File \"/var/task/handler.py\", line 21, in lambda_handler\n    s3.copy_object(CopySource=copy_source, Bucket=bucket, Key=new_key)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 602, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1078, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}